CREATE TABLE customer_request (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT       NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    description VARCHAR(500) NOT NULL,
    checked_by_company VARCHAR(30) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_customer_request_customer_id ON customer_request (customer_id);
CREATE INDEX idx_customer_request_status ON customer_request (status);
