CREATE TABLE supplier_offer (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id      BIGINT        NOT NULL,
    request_id       BIGINT        NOT NULL,
    status           VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    inspection_score INTEGER,
    car_details      VARCHAR(1000) NOT NULL,
    price            DECIMAL(12,2) NOT NULL,
    imported         BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_supplier_offer_request
        FOREIGN KEY (request_id) REFERENCES customer_request (id),

    CONSTRAINT uk_supplier_request
        UNIQUE (supplier_id, request_id)
);

CREATE INDEX idx_supplier_offer_supplier_id ON supplier_offer (supplier_id);
CREATE INDEX idx_supplier_offer_request_id ON supplier_offer (request_id);
CREATE INDEX idx_supplier_offer_status ON supplier_offer (status);
